# https://gohugo.io/getting-started/configuration/
# Site vars (see https://gohugo.io/variables/site/)

baseURL = "https://www.thebiggerguy.com/"
languageCode = "en-gb"

title = "TheBiggerGuy | Guy Taylor"
copyright = "Guy Taylor"
theme = ""

enableGitInfo = true
enableRobotsTXT = true

# Fail if "ref" or "relref" can not be resolved
refLinksErrorLevel = "ERROR"

sectionPagesMenu = "main"

googleAnalytics = "UA-126221439-1"

[author]
    displayName = "Guy Taylor"
    [social]
        twitter = "TheBiggerGuy"

[params]
    # The path must be relative to the static folder 
    favicon = "favicon.ico"

    SiteDescription = "The home of Guy Taylor aka TheBiggerGuy. A Software Engineer working in Edinburgh."

    googleMapsApiKey = "AIzaSyDs8gYGyCWfnn1bxWwZqQL3OXgkdRNOnUA"

# Disable all third party for GDPR
[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = false
        AnonymizeIP = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = true

[imaging]
    resampleFilter = "Lanczos"
    quality = 90

[markup]
    [markup.goldmark.renderer]
      unsafe = true

[module]
    [[module.imports]]
        path = "github.com/twbs/bootstrap"
    [[module.imports.mounts]]
        source = 'scss'
        target = 'assets/scss/bootstrap'
    [[module.imports.mounts]]
        source = 'js'
        target = 'assets/js/bootstrap'
