# Site vars (see https://gohugo.io/variables/site/)
baseURL = "https://www.thebiggerguy.com/"
languageCode = "en-gb"

title = "TheBiggerGuy | Guy Taylor"
copyright = "Guy Taylor"
theme = ""

[author]
    displayName = "Guy Taylor"
    [social]
        twitter = "TheBiggerGuy"

# https://gohugo.io/getting-started/configuration/
## Enable git
enableGitInfo = true
enableRobotsTXT = true
## Fail if "ref" or "relref" can not be resolved
refLinksErrorLevel = "ERROR"

sectionPagesMenu = "main"

[params]
    # The path must be relative to the static folder 
    favicon = "favicon.ico"

    SiteDescription = "The home of Guy Taylor aka TheBiggerGuy. A Software Engineer working in Edinburgh."

    googleMapsApiKey = "AIzaSyDs8gYGyCWfnn1bxWwZqQL3OXgkdRNOnUA"

# Disable all third party for GDPR
[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = true
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        disable = true

[imaging]
    resampleFilter = "Lanczos"
    quality = 90
